### ISSUE TITLE
Invalid arguments order for QueueEntity.php

### ISSUE THREAD

**Issue by CosminIorga** [needle-project/laravel-rabbitmq#41]
Order of arguments are 
queue, passive, durable, exclusive, auto_delete, internal, nowait
but order should be 
queue, passive, durable, exclusive, auto_delete, nowait, arguments, ticket

**Comment by adrian-tilita** [comment]
Tested with `php-amqplib/php-amqplib v3.6.0` and `php-amqplib/php-amqplib v2.10.1` and I got this:
`
    public function queue_declare(
        $queue = '',
        $passive = false,
        $durable = false,
        $exclusive = false,
        $auto_delete = true,
        $nowait = false,
        $arguments = array(),
        $ticket = null
    ) {}
`. 
Also checked the exchange declaration, mainly because of the "internal" is more of an exchange attribute.
Can you provide more info on this matter, please.

**Comment by adrian-tilita** [comment]
Checked this and I think it is closed by #37
